{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 10352,
          "sha512": "371ddcddb7d916f4c0f76dd736325ba72d9eb201aefbe7908e66239ad786639e41ff7c4aa4652bdf94e9dd45d5678ef4e2ac7e1ce993308cb6c09fae4d71a1c4",
          "sha256": "534cd1c0bdf43bd56b03b7ea4e78a836b9eaee02cf893e92d16fe2e199cea505",
          "sha1": "a5cc835f48d874395e0f7be6945f140bc4b33f54",
          "md5": "26417c7250e2b59a39f734233507577f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 10352,
          "sha512": "371ddcddb7d916f4c0f76dd736325ba72d9eb201aefbe7908e66239ad786639e41ff7c4aa4652bdf94e9dd45d5678ef4e2ac7e1ce993308cb6c09fae4d71a1c4",
          "sha256": "534cd1c0bdf43bd56b03b7ea4e78a836b9eaee02cf893e92d16fe2e199cea505",
          "sha1": "a5cc835f48d874395e0f7be6945f140bc4b33f54",
          "md5": "26417c7250e2b59a39f734233507577f"
        }
      ]
    }
  ]
}
