{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 9920,
          "sha512": "5025f34ed1b59f02ca7d77e81d81c60968ca42093054f8804ca9429d660136198aa2d9b8ca8ef7a314a8ee518757efdc0c05c1f1d791925433dbde0ba11962ad",
          "sha256": "ed94742b671b38e41961f8f4f71f3bab2ffa83e880c39c63435d3c24cdb97ffb",
          "sha1": "3d510b6b30925d1aaf2aec86bd368ad42974169d",
          "md5": "341a0bba3b493929dd6076dfc39d8ca5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 9920,
          "sha512": "5025f34ed1b59f02ca7d77e81d81c60968ca42093054f8804ca9429d660136198aa2d9b8ca8ef7a314a8ee518757efdc0c05c1f1d791925433dbde0ba11962ad",
          "sha256": "ed94742b671b38e41961f8f4f71f3bab2ffa83e880c39c63435d3c24cdb97ffb",
          "sha1": "3d510b6b30925d1aaf2aec86bd368ad42974169d",
          "md5": "341a0bba3b493929dd6076dfc39d8ca5"
        }
      ]
    }
  ]
}
