{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 10782,
          "sha512": "6529414bcc1642aef7ede4492a556d30c2f4ccb0d6fa212bad17c4c37aad4b7b518771f9cd1d4a913f163b101b44f9edd4f74298151c18fac73b9568bbf0ee3d",
          "sha256": "7f97cdc0452450274b4aa4913556721319d6ed138f5289533652a8a7130a1fda",
          "sha1": "3e8bf2430fae66f5f6bdb7aec079a5d2929ae247",
          "md5": "460c03794982274942e3f0f8cf230c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 10782,
          "sha512": "6529414bcc1642aef7ede4492a556d30c2f4ccb0d6fa212bad17c4c37aad4b7b518771f9cd1d4a913f163b101b44f9edd4f74298151c18fac73b9568bbf0ee3d",
          "sha256": "7f97cdc0452450274b4aa4913556721319d6ed138f5289533652a8a7130a1fda",
          "sha1": "3e8bf2430fae66f5f6bdb7aec079a5d2929ae247",
          "md5": "460c03794982274942e3f0f8cf230c28"
        }
      ]
    }
  ]
}
