{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "activity",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 26500,
          "sha512": "2b832dd3da5241fe5b4dcb2a73f077674d34e33af034ce7a095d1839b74c86c6f55b9a0498cd6dbb89018da25f8c7ac0e6be86bf379f56753fae21f4985e3b58",
          "sha256": "d6cdda18f2039d7e66b8b9708bef1b54acba78d859d4f37bfefa6e41d30f0e21",
          "sha1": "7888b15e81aab17838ce727bc232bde7a552eb63",
          "md5": "51cb92ebe794d3450d68423c2b69852b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 26500,
          "sha512": "2b832dd3da5241fe5b4dcb2a73f077674d34e33af034ce7a095d1839b74c86c6f55b9a0498cd6dbb89018da25f8c7ac0e6be86bf379f56753fae21f4985e3b58",
          "sha256": "d6cdda18f2039d7e66b8b9708bef1b54acba78d859d4f37bfefa6e41d30f0e21",
          "sha1": "7888b15e81aab17838ce727bc232bde7a552eb63",
          "md5": "51cb92ebe794d3450d68423c2b69852b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-sources.jar",
          "url": "activity-1.0.0-sources.jar",
          "size": 10946,
          "sha512": "54ad2d694c449c37dd4f06187ccc095e94c9e4d22afbd6147fc66c98803987c3eb61858d556dbf6f920cab05784b0402f840a60d0b13de309e4507c55bef408b",
          "sha256": "c60f463e9311a04148ce8d5ae6b9c0ec34e66e0030163aca758c35f22ca9b69b",
          "sha1": "ee28547eba7a78921a1eeb202cf65641f60ee4f7",
          "md5": "033182d730d2e09ffd9f53b2bfaf7ad3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-javadoc.jar",
          "url": "activity-1.0.0-javadoc.jar",
          "size": 379438,
          "sha512": "72926ac79e9a5a061261c4b1f73baec2c558d9441ae0bd900a4019e252f82c130c923e93e385a3f461458fc1b20a2f6eb095564a24f861a3c7b72290cf174a22",
          "sha256": "48447d4322e59eb94159cab9b941d39b777f515787972d615a24f2feb92eccad",
          "sha1": "57bdf6bfcfc79a811a09b896f91ff611296d0d99",
          "md5": "d68cb71e13a4c095e00b11f9424966c4"
        }
      ]
    }
  ]
}
