{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "activity",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 28610,
          "sha512": "e92cb01f312be43280a4a91214ca4dd9f866b6ac0822c279711c66bdcd061065269726d9b55187e8db2ca28841f3b62a143b31e7938b3b176ced494a2310a9fe",
          "sha256": "ed6682e27a79b0e7a39ca854cb4f8c452273ef6798486a367331cb4911a9ea60",
          "sha1": "8b9653499f8bf4a5aaa1fc43ccc8ebf7bec03211",
          "md5": "a36424a0640531e21438e2c215f8da5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 28610,
          "sha512": "e92cb01f312be43280a4a91214ca4dd9f866b6ac0822c279711c66bdcd061065269726d9b55187e8db2ca28841f3b62a143b31e7938b3b176ced494a2310a9fe",
          "sha256": "ed6682e27a79b0e7a39ca854cb4f8c452273ef6798486a367331cb4911a9ea60",
          "sha1": "8b9653499f8bf4a5aaa1fc43ccc8ebf7bec03211",
          "md5": "a36424a0640531e21438e2c215f8da5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-sources.jar",
          "url": "activity-1.0.0-sources.jar",
          "size": 11312,
          "sha512": "4e91fba1e6a03d7e317a9d82abc4a1310c85794c774915ba46e847f397b7a7eb5fbe19784362c36ae77df15854ce22057a11623f9169e79e963bff87defd1d34",
          "sha256": "8eaf41ce6411d5927d9fffeca407ee20c603545e56b6b3467d09c3a551851c55",
          "sha1": "1c96f5f71497e092380929c8a516ba4a3803632d",
          "md5": "ecbbb98b4dc2c8f2d1f7e64f0ddcb3c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-javadoc.jar",
          "url": "activity-1.0.0-javadoc.jar",
          "size": 379420,
          "sha512": "9f02fd97a19f7247c0caf9f68b794971bd91e6b151ed3cf164acd395880d1979df2e039027fca8a6bbac85875fdb847ca08fc31a25c20dfca7d5f45cc440c184",
          "sha256": "6c1b6804bac9473bec1e8b211fa722621924149c4f6bbfbf9c43ad6dc007eb9a",
          "sha1": "2b9d5aaab06efc139fef86b85eb7acc97414c78d",
          "md5": "6521724a7890ca980e96525d4320203e"
        }
      ]
    }
  ]
}
