{
  "formatVersion": "1.1",
  "component": {
    "group": "ori",
    "module": "activity",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 21219,
          "sha512": "994638fcaaccf9dd8295d612de29f38ec0b3e4ceb9450d3320da6b267450fc1f243759127428fb92f4aceebe64a773be191a11e2ecc0c4aa5abbf2d07f4ec87d",
          "sha256": "27d75046301335beaf294827bfab1b1af0db2b2c9d82fe359ef7cb404b7beaad",
          "sha1": "eaa0341abf61d797585b44d9cd5ede9139afd49a",
          "md5": "2d2c7b757fa68c8085073aaf53c3570a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.0.0.aar",
          "url": "activity-1.0.0.aar",
          "size": 21219,
          "sha512": "994638fcaaccf9dd8295d612de29f38ec0b3e4ceb9450d3320da6b267450fc1f243759127428fb92f4aceebe64a773be191a11e2ecc0c4aa5abbf2d07f4ec87d",
          "sha256": "27d75046301335beaf294827bfab1b1af0db2b2c9d82fe359ef7cb404b7beaad",
          "sha1": "eaa0341abf61d797585b44d9cd5ede9139afd49a",
          "md5": "2d2c7b757fa68c8085073aaf53c3570a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-sources.jar",
          "url": "activity-1.0.0-sources.jar",
          "size": 8454,
          "sha512": "3f272d369cdf2de98fcd029c9bac45f3e558f686861d7861c528d75fa86c55c2e6d0a72a208adb7ff90fd898ea9f05a51333e3c5c27cc3ea081bc2452369942d",
          "sha256": "12a5da7dff73d80f40d7a6a877f101363e438e45eac924eeb21b516491bfaaa2",
          "sha1": "6564aa687f5e2553c70bed4b5a229883b71926eb",
          "md5": "645bce75a0742972ae21ae6ddb72db36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.0.0-javadoc.jar",
          "url": "activity-1.0.0-javadoc.jar",
          "size": 387551,
          "sha512": "5af24d365d832dca2486100419cce28a891b0264846bfd199bfcde0fae1a8c5e0f478cc6522f43bde5f5d826ee5aec762f3ce6a634913ee8c0d867a0902b65bb",
          "sha256": "ce5cc7a874f08eb08495420bb3e01eb7b6e7a0c6eaf8d1b2d547cffc552cb3b9",
          "sha1": "899e3898b4fc475ba94ab02a7256fb12daabef6d",
          "md5": "e25edac47e3d7a3af8f627530a94830d"
        }
      ]
    }
  ]
}
